[package]
name = "spatial-version"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
spatial-version-core.workspace = true
spatial-version-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true

[dev-dependencies]
spatial-version-postgis.workspace = true
postgres = "0.19"
tempfile.workspace = true

[lints]
workspace = true
