[package]
name = "geoledger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
geoledger-core.workspace = true
geoledger-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true

[dev-dependencies]
geoledger-postgis.workspace = true
postgres = "0.19"
tempfile.workspace = true

[lints]
workspace = true
