# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from geoledger._internal.v1 import geoledger_pb2 as geoledger_dot_v1_dot_geoledger__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geoledger/v1/geoledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeoLedgerStub(object):
    """GeoJSON remains UTF-8 text to preserve exact 64-bit property numbers.
    A missing Edit.feature is an explicit deletion. No client-supplied identity.
    Revisions are int64; TypeScript SDK represents them as decimal strings.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Info',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.Empty.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.InfoReply.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/geoledger.v1.GeoLedger/CreateProject',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.NameRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/geoledger.v1.GeoLedger/ListProjects',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.PageRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectsReply.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/geoledger.v1.GeoLedger/GetProject',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.SetMember = channel.unary_unary(
                '/geoledger.v1.GeoLedger/SetMember',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.MemberRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
                _registered_method=True)
        self.CreateDataset = channel.unary_unary(
                '/geoledger.v1.GeoLedger/CreateDataset',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetReply.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/geoledger.v1.GeoLedger/ListDatasets',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetsReply.FromString,
                _registered_method=True)
        self.CreateWorkspace = channel.unary_unary(
                '/geoledger.v1.GeoLedger/CreateWorkspace',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
                _registered_method=True)
        self.ListWorkspaces = channel.unary_unary(
                '/geoledger.v1.GeoLedger/ListWorkspaces',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspacesReply.FromString,
                _registered_method=True)
        self.GetWorkspace = channel.unary_unary(
                '/geoledger.v1.GeoLedger/GetWorkspace',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
                _registered_method=True)
        self.Save = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Save',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.SaveRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.SaveReply.FromString,
                _registered_method=True)
        self.Discard = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Discard',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.VersionRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DiscardReply.FromString,
                _registered_method=True)
        self.Features = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Features',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.FeaturesRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.FeaturesReply.FromString,
                _registered_method=True)
        self.Diff = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Diff',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DiffReply.FromString,
                _registered_method=True)
        self.Conflicts = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Conflicts',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ConflictsReply.FromString,
                _registered_method=True)
        self.History = channel.unary_unary(
                '/geoledger.v1.GeoLedger/History',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryReply.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Commit',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.CommitRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.CommitReply.FromString,
                _registered_method=True)
        self.Audit = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Audit',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.AuditReply.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Publish',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.PublishRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.PublishReply.FromString,
                _registered_method=True)
        self.Resolve = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Resolve',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveReply.FromString,
                _registered_method=True)
        self.Rebase = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Rebase',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.RebaseReply.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/geoledger.v1.GeoLedger/Restore',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.RestoreRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/geoledger.v1.GeoLedger/ListMembers',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.MembersReply.FromString,
                _registered_method=True)
        self.RemoveMember = channel.unary_unary(
                '/geoledger.v1.GeoLedger/RemoveMember',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.MemberRefRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
                _registered_method=True)
        self.ArchiveProject = channel.unary_unary(
                '/geoledger.v1.GeoLedger/ArchiveProject',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.ArchiveProjectRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/geoledger.v1.GeoLedger/DeleteProject',
                request_serializer=geoledger_dot_v1_dot_geoledger__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
                _registered_method=True)


class GeoLedgerServicer(object):
    """GeoJSON remains UTF-8 text to preserve exact 64-bit property numbers.
    A missing Edit.feature is an explicit deletion. No client-supplied identity.
    Revisions are int64; TypeScript SDK represents them as decimal strings.
    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Features(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Conflicts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Audit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rebase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchiveProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoLedgerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.Empty.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.InfoReply.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.NameRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.PageRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectsReply.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.SerializeToString,
            ),
            'SetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMember,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.MemberRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.SerializeToString,
            ),
            'CreateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDataset,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetReply.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.DatasetsReply.SerializeToString,
            ),
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.SerializeToString,
            ),
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspacesReply.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.SaveRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.SaveReply.SerializeToString,
            ),
            'Discard': grpc.unary_unary_rpc_method_handler(
                    servicer.Discard,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.VersionRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.DiscardReply.SerializeToString,
            ),
            'Features': grpc.unary_unary_rpc_method_handler(
                    servicer.Features,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.FeaturesRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.FeaturesReply.SerializeToString,
            ),
            'Diff': grpc.unary_unary_rpc_method_handler(
                    servicer.Diff,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.DiffReply.SerializeToString,
            ),
            'Conflicts': grpc.unary_unary_rpc_method_handler(
                    servicer.Conflicts,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ConflictsReply.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryReply.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.CommitRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.CommitReply.SerializeToString,
            ),
            'Audit': grpc.unary_unary_rpc_method_handler(
                    servicer.Audit,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.AuditReply.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.PublishRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.PublishReply.SerializeToString,
            ),
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveReply.SerializeToString,
            ),
            'Rebase': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebase,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.RebaseReply.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.RestoreRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.MembersReply.SerializeToString,
            ),
            'RemoveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMember,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.MemberRefRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.SerializeToString,
            ),
            'ArchiveProject': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchiveProject,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.ArchiveProjectRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=geoledger_dot_v1_dot_geoledger__pb2.DeleteProjectRequest.FromString,
                    response_serializer=geoledger_dot_v1_dot_geoledger__pb2.OkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geoledger.v1.GeoLedger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geoledger.v1.GeoLedger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeoLedger(object):
    """GeoJSON remains UTF-8 text to preserve exact 64-bit property numbers.
    A missing Edit.feature is an explicit deletion. No client-supplied identity.
    Revisions are int64; TypeScript SDK represents them as decimal strings.
    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Info',
            geoledger_dot_v1_dot_geoledger__pb2.Empty.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.InfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/CreateProject',
            geoledger_dot_v1_dot_geoledger__pb2.NameRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/ListProjects',
            geoledger_dot_v1_dot_geoledger__pb2.PageRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ProjectsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/GetProject',
            geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/SetMember',
            geoledger_dot_v1_dot_geoledger__pb2.MemberRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/CreateDataset',
            geoledger_dot_v1_dot_geoledger__pb2.DatasetRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.DatasetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/ListDatasets',
            geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.DatasetsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/CreateWorkspace',
            geoledger_dot_v1_dot_geoledger__pb2.ProjectRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/ListWorkspaces',
            geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.WorkspacesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/GetWorkspace',
            geoledger_dot_v1_dot_geoledger__pb2.WorkspaceRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Save',
            geoledger_dot_v1_dot_geoledger__pb2.SaveRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.SaveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Discard',
            geoledger_dot_v1_dot_geoledger__pb2.VersionRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.DiscardReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Features(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Features',
            geoledger_dot_v1_dot_geoledger__pb2.FeaturesRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.FeaturesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Diff',
            geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.DiffReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Conflicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Conflicts',
            geoledger_dot_v1_dot_geoledger__pb2.DiffRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ConflictsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/History',
            geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.HistoryReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Commit',
            geoledger_dot_v1_dot_geoledger__pb2.CommitRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.CommitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Audit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Audit',
            geoledger_dot_v1_dot_geoledger__pb2.HistoryRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.AuditReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Publish',
            geoledger_dot_v1_dot_geoledger__pb2.PublishRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.PublishReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Resolve',
            geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ResolveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Rebase',
            geoledger_dot_v1_dot_geoledger__pb2.ResolveRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.RebaseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/Restore',
            geoledger_dot_v1_dot_geoledger__pb2.RestoreRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.WorkspaceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/ListMembers',
            geoledger_dot_v1_dot_geoledger__pb2.ProjectPageRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.MembersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/RemoveMember',
            geoledger_dot_v1_dot_geoledger__pb2.MemberRefRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchiveProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/ArchiveProject',
            geoledger_dot_v1_dot_geoledger__pb2.ArchiveProjectRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.ProjectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoledger.v1.GeoLedger/DeleteProject',
            geoledger_dot_v1_dot_geoledger__pb2.DeleteProjectRequest.SerializeToString,
            geoledger_dot_v1_dot_geoledger__pb2.OkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
