// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: geoledger/v1/geoledger.proto

package geoledgerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoLedger_Info_FullMethodName            = "/geoledger.v1.GeoLedger/Info"
	GeoLedger_CreateProject_FullMethodName   = "/geoledger.v1.GeoLedger/CreateProject"
	GeoLedger_ListProjects_FullMethodName    = "/geoledger.v1.GeoLedger/ListProjects"
	GeoLedger_GetProject_FullMethodName      = "/geoledger.v1.GeoLedger/GetProject"
	GeoLedger_SetMember_FullMethodName       = "/geoledger.v1.GeoLedger/SetMember"
	GeoLedger_RenameProject_FullMethodName   = "/geoledger.v1.GeoLedger/RenameProject"
	GeoLedger_RenameDataset_FullMethodName   = "/geoledger.v1.GeoLedger/RenameDataset"
	GeoLedger_DeleteDataset_FullMethodName   = "/geoledger.v1.GeoLedger/DeleteDataset"
	GeoLedger_CreateDataset_FullMethodName   = "/geoledger.v1.GeoLedger/CreateDataset"
	GeoLedger_ListDatasets_FullMethodName    = "/geoledger.v1.GeoLedger/ListDatasets"
	GeoLedger_CreateWorkspace_FullMethodName = "/geoledger.v1.GeoLedger/CreateWorkspace"
	GeoLedger_ListWorkspaces_FullMethodName  = "/geoledger.v1.GeoLedger/ListWorkspaces"
	GeoLedger_GetWorkspace_FullMethodName    = "/geoledger.v1.GeoLedger/GetWorkspace"
	GeoLedger_Save_FullMethodName            = "/geoledger.v1.GeoLedger/Save"
	GeoLedger_SaveStream_FullMethodName      = "/geoledger.v1.GeoLedger/SaveStream"
	GeoLedger_Discard_FullMethodName         = "/geoledger.v1.GeoLedger/Discard"
	GeoLedger_Features_FullMethodName        = "/geoledger.v1.GeoLedger/Features"
	GeoLedger_FeaturesStream_FullMethodName  = "/geoledger.v1.GeoLedger/FeaturesStream"
	GeoLedger_Diff_FullMethodName            = "/geoledger.v1.GeoLedger/Diff"
	GeoLedger_Conflicts_FullMethodName       = "/geoledger.v1.GeoLedger/Conflicts"
	GeoLedger_History_FullMethodName         = "/geoledger.v1.GeoLedger/History"
	GeoLedger_Commit_FullMethodName          = "/geoledger.v1.GeoLedger/Commit"
	GeoLedger_Audit_FullMethodName           = "/geoledger.v1.GeoLedger/Audit"
	GeoLedger_Publish_FullMethodName         = "/geoledger.v1.GeoLedger/Publish"
	GeoLedger_Resolve_FullMethodName         = "/geoledger.v1.GeoLedger/Resolve"
	GeoLedger_Rebase_FullMethodName          = "/geoledger.v1.GeoLedger/Rebase"
	GeoLedger_Restore_FullMethodName         = "/geoledger.v1.GeoLedger/Restore"
	GeoLedger_ListMembers_FullMethodName     = "/geoledger.v1.GeoLedger/ListMembers"
	GeoLedger_RemoveMember_FullMethodName    = "/geoledger.v1.GeoLedger/RemoveMember"
	GeoLedger_ArchiveProject_FullMethodName  = "/geoledger.v1.GeoLedger/ArchiveProject"
	GeoLedger_DeleteProject_FullMethodName   = "/geoledger.v1.GeoLedger/DeleteProject"
)

// GeoLedgerClient is the client API for GeoLedger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GeoJSON remains UTF-8 text to preserve exact 64-bit property numbers.
// A missing Edit.feature is an explicit deletion. No client-supplied identity.
// Revisions are int64; TypeScript SDK represents them as decimal strings.
type GeoLedgerClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoReply, error)
	CreateProject(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	ListProjects(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ProjectsReply, error)
	GetProject(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	SetMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*OkReply, error)
	RenameProject(ctx context.Context, in *RenameProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	RenameDataset(ctx context.Context, in *RenameDatasetRequest, opts ...grpc.CallOption) (*DatasetReply, error)
	DeleteDataset(ctx context.Context, in *DeleteDatasetRequest, opts ...grpc.CallOption) (*OkReply, error)
	CreateDataset(ctx context.Context, in *DatasetRequest, opts ...grpc.CallOption) (*DatasetReply, error)
	ListDatasets(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*DatasetsReply, error)
	CreateWorkspace(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*WorkspaceReply, error)
	ListWorkspaces(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*WorkspacesReply, error)
	GetWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceReply, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error)
	// Concatenated chunks encode one SaveRequest; apply atomically only after EOF.
	SaveStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, SaveReply], error)
	Discard(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*DiscardReply, error)
	Features(ctx context.Context, in *FeaturesRequest, opts ...grpc.CallOption) (*FeaturesReply, error)
	// Concatenated chunks encode one snapshot-consistent FeaturesReply.
	FeaturesStream(ctx context.Context, in *FeaturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffReply, error)
	Conflicts(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*ConflictsReply, error)
	History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryReply, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error)
	Audit(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*AuditReply, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error)
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveReply, error)
	Rebase(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*RebaseReply, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*WorkspaceReply, error)
	ListMembers(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*MembersReply, error)
	RemoveMember(ctx context.Context, in *MemberRefRequest, opts ...grpc.CallOption) (*OkReply, error)
	ArchiveProject(ctx context.Context, in *ArchiveProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*OkReply, error)
}

type geoLedgerClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoLedgerClient(cc grpc.ClientConnInterface) GeoLedgerClient {
	return &geoLedgerClient{cc}
}

func (c *geoLedgerClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoReply)
	err := c.cc.Invoke(ctx, GeoLedger_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) CreateProject(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, GeoLedger_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) ListProjects(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ProjectsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectsReply)
	err := c.cc.Invoke(ctx, GeoLedger_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) GetProject(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, GeoLedger_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) SetMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*OkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkReply)
	err := c.cc.Invoke(ctx, GeoLedger_SetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) RenameProject(ctx context.Context, in *RenameProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, GeoLedger_RenameProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) RenameDataset(ctx context.Context, in *RenameDatasetRequest, opts ...grpc.CallOption) (*DatasetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetReply)
	err := c.cc.Invoke(ctx, GeoLedger_RenameDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) DeleteDataset(ctx context.Context, in *DeleteDatasetRequest, opts ...grpc.CallOption) (*OkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkReply)
	err := c.cc.Invoke(ctx, GeoLedger_DeleteDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) CreateDataset(ctx context.Context, in *DatasetRequest, opts ...grpc.CallOption) (*DatasetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetReply)
	err := c.cc.Invoke(ctx, GeoLedger_CreateDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) ListDatasets(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*DatasetsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatasetsReply)
	err := c.cc.Invoke(ctx, GeoLedger_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) CreateWorkspace(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*WorkspaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceReply)
	err := c.cc.Invoke(ctx, GeoLedger_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) ListWorkspaces(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*WorkspacesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspacesReply)
	err := c.cc.Invoke(ctx, GeoLedger_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) GetWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceReply)
	err := c.cc.Invoke(ctx, GeoLedger_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, GeoLedger_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) SaveStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, SaveReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeoLedger_ServiceDesc.Streams[0], GeoLedger_SaveStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, SaveReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoLedger_SaveStreamClient = grpc.ClientStreamingClient[DataChunk, SaveReply]

func (c *geoLedgerClient) Discard(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*DiscardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscardReply)
	err := c.cc.Invoke(ctx, GeoLedger_Discard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Features(ctx context.Context, in *FeaturesRequest, opts ...grpc.CallOption) (*FeaturesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeaturesReply)
	err := c.cc.Invoke(ctx, GeoLedger_Features_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) FeaturesStream(ctx context.Context, in *FeaturesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeoLedger_ServiceDesc.Streams[1], GeoLedger_FeaturesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FeaturesRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoLedger_FeaturesStreamClient = grpc.ServerStreamingClient[DataChunk]

func (c *geoLedgerClient) Diff(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffReply)
	err := c.cc.Invoke(ctx, GeoLedger_Diff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Conflicts(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*ConflictsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConflictsReply)
	err := c.cc.Invoke(ctx, GeoLedger_Conflicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) History(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryReply)
	err := c.cc.Invoke(ctx, GeoLedger_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitReply)
	err := c.cc.Invoke(ctx, GeoLedger_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Audit(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*AuditReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditReply)
	err := c.cc.Invoke(ctx, GeoLedger_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishReply)
	err := c.cc.Invoke(ctx, GeoLedger_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveReply)
	err := c.cc.Invoke(ctx, GeoLedger_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Rebase(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*RebaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebaseReply)
	err := c.cc.Invoke(ctx, GeoLedger_Rebase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*WorkspaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceReply)
	err := c.cc.Invoke(ctx, GeoLedger_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) ListMembers(ctx context.Context, in *ProjectPageRequest, opts ...grpc.CallOption) (*MembersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembersReply)
	err := c.cc.Invoke(ctx, GeoLedger_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) RemoveMember(ctx context.Context, in *MemberRefRequest, opts ...grpc.CallOption) (*OkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkReply)
	err := c.cc.Invoke(ctx, GeoLedger_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) ArchiveProject(ctx context.Context, in *ArchiveProjectRequest, opts ...grpc.CallOption) (*ProjectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectReply)
	err := c.cc.Invoke(ctx, GeoLedger_ArchiveProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLedgerClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*OkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkReply)
	err := c.cc.Invoke(ctx, GeoLedger_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoLedgerServer is the server API for GeoLedger service.
// All implementations must embed UnimplementedGeoLedgerServer
// for forward compatibility.
//
// GeoJSON remains UTF-8 text to preserve exact 64-bit property numbers.
// A missing Edit.feature is an explicit deletion. No client-supplied identity.
// Revisions are int64; TypeScript SDK represents them as decimal strings.
type GeoLedgerServer interface {
	Info(context.Context, *Empty) (*InfoReply, error)
	CreateProject(context.Context, *NameRequest) (*ProjectReply, error)
	ListProjects(context.Context, *PageRequest) (*ProjectsReply, error)
	GetProject(context.Context, *ProjectRequest) (*ProjectReply, error)
	SetMember(context.Context, *MemberRequest) (*OkReply, error)
	RenameProject(context.Context, *RenameProjectRequest) (*ProjectReply, error)
	RenameDataset(context.Context, *RenameDatasetRequest) (*DatasetReply, error)
	DeleteDataset(context.Context, *DeleteDatasetRequest) (*OkReply, error)
	CreateDataset(context.Context, *DatasetRequest) (*DatasetReply, error)
	ListDatasets(context.Context, *ProjectPageRequest) (*DatasetsReply, error)
	CreateWorkspace(context.Context, *ProjectRequest) (*WorkspaceReply, error)
	ListWorkspaces(context.Context, *ProjectPageRequest) (*WorkspacesReply, error)
	GetWorkspace(context.Context, *WorkspaceRequest) (*WorkspaceReply, error)
	Save(context.Context, *SaveRequest) (*SaveReply, error)
	// Concatenated chunks encode one SaveRequest; apply atomically only after EOF.
	SaveStream(grpc.ClientStreamingServer[DataChunk, SaveReply]) error
	Discard(context.Context, *VersionRequest) (*DiscardReply, error)
	Features(context.Context, *FeaturesRequest) (*FeaturesReply, error)
	// Concatenated chunks encode one snapshot-consistent FeaturesReply.
	FeaturesStream(*FeaturesRequest, grpc.ServerStreamingServer[DataChunk]) error
	Diff(context.Context, *DiffRequest) (*DiffReply, error)
	Conflicts(context.Context, *DiffRequest) (*ConflictsReply, error)
	History(context.Context, *HistoryRequest) (*HistoryReply, error)
	Commit(context.Context, *CommitRequest) (*CommitReply, error)
	Audit(context.Context, *HistoryRequest) (*AuditReply, error)
	Publish(context.Context, *PublishRequest) (*PublishReply, error)
	Resolve(context.Context, *ResolveRequest) (*ResolveReply, error)
	Rebase(context.Context, *ResolveRequest) (*RebaseReply, error)
	Restore(context.Context, *RestoreRequest) (*WorkspaceReply, error)
	ListMembers(context.Context, *ProjectPageRequest) (*MembersReply, error)
	RemoveMember(context.Context, *MemberRefRequest) (*OkReply, error)
	ArchiveProject(context.Context, *ArchiveProjectRequest) (*ProjectReply, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*OkReply, error)
	mustEmbedUnimplementedGeoLedgerServer()
}

// UnimplementedGeoLedgerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoLedgerServer struct{}

func (UnimplementedGeoLedgerServer) Info(context.Context, *Empty) (*InfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedGeoLedgerServer) CreateProject(context.Context, *NameRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedGeoLedgerServer) ListProjects(context.Context, *PageRequest) (*ProjectsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedGeoLedgerServer) GetProject(context.Context, *ProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedGeoLedgerServer) SetMember(context.Context, *MemberRequest) (*OkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMember not implemented")
}
func (UnimplementedGeoLedgerServer) RenameProject(context.Context, *RenameProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameProject not implemented")
}
func (UnimplementedGeoLedgerServer) RenameDataset(context.Context, *RenameDatasetRequest) (*DatasetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameDataset not implemented")
}
func (UnimplementedGeoLedgerServer) DeleteDataset(context.Context, *DeleteDatasetRequest) (*OkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataset not implemented")
}
func (UnimplementedGeoLedgerServer) CreateDataset(context.Context, *DatasetRequest) (*DatasetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataset not implemented")
}
func (UnimplementedGeoLedgerServer) ListDatasets(context.Context, *ProjectPageRequest) (*DatasetsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedGeoLedgerServer) CreateWorkspace(context.Context, *ProjectRequest) (*WorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedGeoLedgerServer) ListWorkspaces(context.Context, *ProjectPageRequest) (*WorkspacesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedGeoLedgerServer) GetWorkspace(context.Context, *WorkspaceRequest) (*WorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedGeoLedgerServer) Save(context.Context, *SaveRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedGeoLedgerServer) SaveStream(grpc.ClientStreamingServer[DataChunk, SaveReply]) error {
	return status.Errorf(codes.Unimplemented, "method SaveStream not implemented")
}
func (UnimplementedGeoLedgerServer) Discard(context.Context, *VersionRequest) (*DiscardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discard not implemented")
}
func (UnimplementedGeoLedgerServer) Features(context.Context, *FeaturesRequest) (*FeaturesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Features not implemented")
}
func (UnimplementedGeoLedgerServer) FeaturesStream(*FeaturesRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Errorf(codes.Unimplemented, "method FeaturesStream not implemented")
}
func (UnimplementedGeoLedgerServer) Diff(context.Context, *DiffRequest) (*DiffReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diff not implemented")
}
func (UnimplementedGeoLedgerServer) Conflicts(context.Context, *DiffRequest) (*ConflictsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Conflicts not implemented")
}
func (UnimplementedGeoLedgerServer) History(context.Context, *HistoryRequest) (*HistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedGeoLedgerServer) Commit(context.Context, *CommitRequest) (*CommitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedGeoLedgerServer) Audit(context.Context, *HistoryRequest) (*AuditReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedGeoLedgerServer) Publish(context.Context, *PublishRequest) (*PublishReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedGeoLedgerServer) Resolve(context.Context, *ResolveRequest) (*ResolveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedGeoLedgerServer) Rebase(context.Context, *ResolveRequest) (*RebaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rebase not implemented")
}
func (UnimplementedGeoLedgerServer) Restore(context.Context, *RestoreRequest) (*WorkspaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedGeoLedgerServer) ListMembers(context.Context, *ProjectPageRequest) (*MembersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGeoLedgerServer) RemoveMember(context.Context, *MemberRefRequest) (*OkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedGeoLedgerServer) ArchiveProject(context.Context, *ArchiveProjectRequest) (*ProjectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveProject not implemented")
}
func (UnimplementedGeoLedgerServer) DeleteProject(context.Context, *DeleteProjectRequest) (*OkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedGeoLedgerServer) mustEmbedUnimplementedGeoLedgerServer() {}
func (UnimplementedGeoLedgerServer) testEmbeddedByValue()                   {}

// UnsafeGeoLedgerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoLedgerServer will
// result in compilation errors.
type UnsafeGeoLedgerServer interface {
	mustEmbedUnimplementedGeoLedgerServer()
}

func RegisterGeoLedgerServer(s grpc.ServiceRegistrar, srv GeoLedgerServer) {
	// If the following call pancis, it indicates UnimplementedGeoLedgerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoLedger_ServiceDesc, srv)
}

func _GeoLedger_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).CreateProject(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).ListProjects(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).GetProject(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_SetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).SetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_SetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).SetMember(ctx, req.(*MemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_RenameProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).RenameProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_RenameProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).RenameProject(ctx, req.(*RenameProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_RenameDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).RenameDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_RenameDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).RenameDataset(ctx, req.(*RenameDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_DeleteDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).DeleteDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_DeleteDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).DeleteDataset(ctx, req.(*DeleteDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_CreateDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).CreateDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_CreateDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).CreateDataset(ctx, req.(*DatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).ListDatasets(ctx, req.(*ProjectPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).CreateWorkspace(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).ListWorkspaces(ctx, req.(*ProjectPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).GetWorkspace(ctx, req.(*WorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_SaveStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeoLedgerServer).SaveStream(&grpc.GenericServerStream[DataChunk, SaveReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoLedger_SaveStreamServer = grpc.ClientStreamingServer[DataChunk, SaveReply]

func _GeoLedger_Discard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Discard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Discard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Discard(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Features_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeaturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Features(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Features_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Features(ctx, req.(*FeaturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_FeaturesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FeaturesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeoLedgerServer).FeaturesStream(m, &grpc.GenericServerStream[FeaturesRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeoLedger_FeaturesStreamServer = grpc.ServerStreamingServer[DataChunk]

func _GeoLedger_Diff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Diff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Diff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Diff(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Conflicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Conflicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Conflicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Conflicts(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).History(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Audit(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Rebase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Rebase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Rebase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Rebase(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).ListMembers(ctx, req.(*ProjectPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).RemoveMember(ctx, req.(*MemberRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_ArchiveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).ArchiveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_ArchiveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).ArchiveProject(ctx, req.(*ArchiveProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLedger_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLedgerServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLedger_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLedgerServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoLedger_ServiceDesc is the grpc.ServiceDesc for GeoLedger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoLedger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geoledger.v1.GeoLedger",
	HandlerType: (*GeoLedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _GeoLedger_Info_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _GeoLedger_CreateProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _GeoLedger_ListProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _GeoLedger_GetProject_Handler,
		},
		{
			MethodName: "SetMember",
			Handler:    _GeoLedger_SetMember_Handler,
		},
		{
			MethodName: "RenameProject",
			Handler:    _GeoLedger_RenameProject_Handler,
		},
		{
			MethodName: "RenameDataset",
			Handler:    _GeoLedger_RenameDataset_Handler,
		},
		{
			MethodName: "DeleteDataset",
			Handler:    _GeoLedger_DeleteDataset_Handler,
		},
		{
			MethodName: "CreateDataset",
			Handler:    _GeoLedger_CreateDataset_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _GeoLedger_ListDatasets_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _GeoLedger_CreateWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _GeoLedger_ListWorkspaces_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _GeoLedger_GetWorkspace_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _GeoLedger_Save_Handler,
		},
		{
			MethodName: "Discard",
			Handler:    _GeoLedger_Discard_Handler,
		},
		{
			MethodName: "Features",
			Handler:    _GeoLedger_Features_Handler,
		},
		{
			MethodName: "Diff",
			Handler:    _GeoLedger_Diff_Handler,
		},
		{
			MethodName: "Conflicts",
			Handler:    _GeoLedger_Conflicts_Handler,
		},
		{
			MethodName: "History",
			Handler:    _GeoLedger_History_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _GeoLedger_Commit_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _GeoLedger_Audit_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _GeoLedger_Publish_Handler,
		},
		{
			MethodName: "Resolve",
			Handler:    _GeoLedger_Resolve_Handler,
		},
		{
			MethodName: "Rebase",
			Handler:    _GeoLedger_Rebase_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _GeoLedger_Restore_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GeoLedger_ListMembers_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _GeoLedger_RemoveMember_Handler,
		},
		{
			MethodName: "ArchiveProject",
			Handler:    _GeoLedger_ArchiveProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _GeoLedger_DeleteProject_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveStream",
			Handler:       _GeoLedger_SaveStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FeaturesStream",
			Handler:       _GeoLedger_FeaturesStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "geoledger/v1/geoledger.proto",
}
