// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: geoledger/v1/geoledger.proto

package geoledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{0}
}

func (x *NameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRequest) Reset() {
	*x = ProjectRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRequest) ProtoMessage() {}

func (x *ProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRequest.ProtoReflect.Descriptor instead.
func (*ProjectRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         string                 `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{2}
}

func (x *PageRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *PageRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ProjectPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	After         string                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectPageRequest) Reset() {
	*x = ProjectPageRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectPageRequest) ProtoMessage() {}

func (x *ProjectPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectPageRequest.ProtoReflect.Descriptor instead.
func (*ProjectPageRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectPageRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectPageRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ProjectPageRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type MemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRequest) Reset() {
	*x = MemberRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRequest) ProtoMessage() {}

func (x *MemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRequest.ProtoReflect.Descriptor instead.
func (*MemberRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{4}
}

func (x *MemberRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MemberRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type DatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetRequest) Reset() {
	*x = DatasetRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetRequest) ProtoMessage() {}

func (x *DatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetRequest.ProtoReflect.Descriptor instead.
func (*DatasetRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{5}
}

func (x *DatasetRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DatasetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceRequest) Reset() {
	*x = WorkspaceRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRequest) ProtoMessage() {}

func (x *WorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{6}
}

func (x *WorkspaceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *WorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type VersionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Project                  string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace                string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	ExpectedWorkspaceVersion int64                  `protobuf:"varint,3,opt,name=expected_workspace_version,json=expectedWorkspaceVersion,proto3" json:"expected_workspace_version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{7}
}

func (x *VersionRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *VersionRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *VersionRequest) GetExpectedWorkspaceVersion() int64 {
	if x != nil {
		return x.ExpectedWorkspaceVersion
	}
	return 0
}

type Feature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Geojson       string                 `protobuf:"bytes,1,opt,name=geojson,proto3" json:"geojson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{8}
}

func (x *Feature) GetGeojson() string {
	if x != nil {
		return x.Geojson
	}
	return ""
}

type Edit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	FeatureId     string                 `protobuf:"bytes,2,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Feature       *Feature               `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edit) Reset() {
	*x = Edit{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edit) ProtoMessage() {}

func (x *Edit) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edit.ProtoReflect.Descriptor instead.
func (*Edit) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{9}
}

func (x *Edit) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Edit) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *Edit) GetFeature() *Feature {
	if x != nil {
		return x.Feature
	}
	return nil
}

type SaveRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Project                  string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace                string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	ExpectedWorkspaceVersion int64                  `protobuf:"varint,3,opt,name=expected_workspace_version,json=expectedWorkspaceVersion,proto3" json:"expected_workspace_version,omitempty"`
	Edits                    []*Edit                `protobuf:"bytes,4,rep,name=edits,proto3" json:"edits,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{10}
}

func (x *SaveRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SaveRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *SaveRequest) GetExpectedWorkspaceVersion() int64 {
	if x != nil {
		return x.ExpectedWorkspaceVersion
	}
	return 0
}

func (x *SaveRequest) GetEdits() []*Edit {
	if x != nil {
		return x.Edits
	}
	return nil
}

type FeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Dataset       string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Workspace     *string                `protobuf:"bytes,3,opt,name=workspace,proto3,oneof" json:"workspace,omitempty"`
	Revision      *int64                 `protobuf:"varint,4,opt,name=revision,proto3,oneof" json:"revision,omitempty"`
	FeatureId     *string                `protobuf:"bytes,5,opt,name=feature_id,json=featureId,proto3,oneof" json:"feature_id,omitempty"`
	Bbox          []float64              `protobuf:"fixed64,6,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`
	After         string                 `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,8,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturesRequest) Reset() {
	*x = FeaturesRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturesRequest) ProtoMessage() {}

func (x *FeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturesRequest.ProtoReflect.Descriptor instead.
func (*FeaturesRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{11}
}

func (x *FeaturesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *FeaturesRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *FeaturesRequest) GetWorkspace() string {
	if x != nil && x.Workspace != nil {
		return *x.Workspace
	}
	return ""
}

func (x *FeaturesRequest) GetRevision() int64 {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return 0
}

func (x *FeaturesRequest) GetFeatureId() string {
	if x != nil && x.FeatureId != nil {
		return *x.FeatureId
	}
	return ""
}

func (x *FeaturesRequest) GetBbox() []float64 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *FeaturesRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *FeaturesRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type DiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	After         string                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{12}
}

func (x *DiffRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DiffRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DiffRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *DiffRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	After         int64                  `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *HistoryRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	After         string                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         *int64                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{14}
}

func (x *CommitRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CommitRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CommitRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *CommitRequest) GetLimit() int64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type PublishRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Project                  string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace                string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	ExpectedWorkspaceVersion int64                  `protobuf:"varint,3,opt,name=expected_workspace_version,json=expectedWorkspaceVersion,proto3" json:"expected_workspace_version,omitempty"`
	RequestId                string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message                  string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{15}
}

func (x *PublishRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *PublishRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *PublishRequest) GetExpectedWorkspaceVersion() int64 {
	if x != nil {
		return x.ExpectedWorkspaceVersion
	}
	return 0
}

func (x *PublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublishRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Project                  string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Workspace                string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	ExpectedWorkspaceVersion int64                  `protobuf:"varint,3,opt,name=expected_workspace_version,json=expectedWorkspaceVersion,proto3" json:"expected_workspace_version,omitempty"`
	ExpectedHead             int64                  `protobuf:"varint,4,opt,name=expected_head,json=expectedHead,proto3" json:"expected_head,omitempty"`
	Resolutions              []*Edit                `protobuf:"bytes,5,rep,name=resolutions,proto3" json:"resolutions,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ResolveRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ResolveRequest) GetExpectedWorkspaceVersion() int64 {
	if x != nil {
		return x.ExpectedWorkspaceVersion
	}
	return 0
}

func (x *ResolveRequest) GetExpectedHead() int64 {
	if x != nil {
		return x.ExpectedHead
	}
	return 0
}

func (x *ResolveRequest) GetResolutions() []*Edit {
	if x != nil {
		return x.Resolutions
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Revision      int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{17}
}

func (x *RestoreRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RestoreRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{18}
}

type InfoReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Backend         string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	FormatVersion   uint32                 `protobuf:"varint,3,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	MaxRequestBytes uint32                 `protobuf:"varint,4,opt,name=max_request_bytes,json=maxRequestBytes,proto3" json:"max_request_bytes,omitempty"`
	MaxFeatureBytes uint32                 `protobuf:"varint,5,opt,name=max_feature_bytes,json=maxFeatureBytes,proto3" json:"max_feature_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InfoReply) Reset() {
	*x = InfoReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReply) ProtoMessage() {}

func (x *InfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReply.ProtoReflect.Descriptor instead.
func (*InfoReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{19}
}

func (x *InfoReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoReply) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *InfoReply) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *InfoReply) GetMaxRequestBytes() uint32 {
	if x != nil {
		return x.MaxRequestBytes
	}
	return 0
}

func (x *InfoReply) GetMaxFeatureBytes() uint32 {
	if x != nil {
		return x.MaxFeatureBytes
	}
	return 0
}

type ProjectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Head          int64                  `protobuf:"varint,3,opt,name=head,proto3" json:"head,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectReply) Reset() {
	*x = ProjectReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectReply) ProtoMessage() {}

func (x *ProjectReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectReply.ProtoReflect.Descriptor instead.
func (*ProjectReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{20}
}

func (x *ProjectReply) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ProjectReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectReply) GetHead() int64 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *ProjectReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ProjectsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectReply        `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectsReply) Reset() {
	*x = ProjectsReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectsReply) ProtoMessage() {}

func (x *ProjectsReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectsReply.ProtoReflect.Descriptor instead.
func (*ProjectsReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{21}
}

func (x *ProjectsReply) GetProjects() []*ProjectReply {
	if x != nil {
		return x.Projects
	}
	return nil
}

type OkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OkReply) Reset() {
	*x = OkReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OkReply) ProtoMessage() {}

func (x *OkReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OkReply.ProtoReflect.Descriptor instead.
func (*OkReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{22}
}

func (x *OkReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DatasetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetReply) Reset() {
	*x = DatasetReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetReply) ProtoMessage() {}

func (x *DatasetReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetReply.ProtoReflect.Descriptor instead.
func (*DatasetReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{23}
}

func (x *DatasetReply) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *DatasetReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DatasetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*DatasetReply        `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetsReply) Reset() {
	*x = DatasetsReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetsReply) ProtoMessage() {}

func (x *DatasetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetsReply.ProtoReflect.Descriptor instead.
func (*DatasetsReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{24}
}

func (x *DatasetsReply) GetDatasets() []*DatasetReply {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type WorkspaceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	BaseRevision  int64                  `protobuf:"varint,2,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceReply) Reset() {
	*x = WorkspaceReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceReply) ProtoMessage() {}

func (x *WorkspaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceReply.ProtoReflect.Descriptor instead.
func (*WorkspaceReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{25}
}

func (x *WorkspaceReply) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *WorkspaceReply) GetBaseRevision() int64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

func (x *WorkspaceReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WorkspaceReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WorkspacesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceReply      `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspacesReply) Reset() {
	*x = WorkspacesReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspacesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspacesReply) ProtoMessage() {}

func (x *WorkspacesReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspacesReply.ProtoReflect.Descriptor instead.
func (*WorkspacesReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{26}
}

func (x *WorkspacesReply) GetWorkspaces() []*WorkspaceReply {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type SaveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Changes       int64                  `protobuf:"varint,2,opt,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveReply) Reset() {
	*x = SaveReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveReply) ProtoMessage() {}

func (x *SaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveReply.ProtoReflect.Descriptor instead.
func (*SaveReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{27}
}

func (x *SaveReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SaveReply) GetChanges() int64 {
	if x != nil {
		return x.Changes
	}
	return 0
}

type DiscardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardReply) Reset() {
	*x = DiscardReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardReply) ProtoMessage() {}

func (x *DiscardReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardReply.ProtoReflect.Descriptor instead.
func (*DiscardReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{28}
}

func (x *DiscardReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DiscardReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FeaturesReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Features         []*Feature             `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	Revision         int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	WorkspaceVersion *int64                 `protobuf:"varint,3,opt,name=workspace_version,json=workspaceVersion,proto3,oneof" json:"workspace_version,omitempty"`
	NextAfter        *string                `protobuf:"bytes,4,opt,name=next_after,json=nextAfter,proto3,oneof" json:"next_after,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeaturesReply) Reset() {
	*x = FeaturesReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturesReply) ProtoMessage() {}

func (x *FeaturesReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturesReply.ProtoReflect.Descriptor instead.
func (*FeaturesReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{29}
}

func (x *FeaturesReply) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *FeaturesReply) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *FeaturesReply) GetWorkspaceVersion() int64 {
	if x != nil && x.WorkspaceVersion != nil {
		return *x.WorkspaceVersion
	}
	return 0
}

func (x *FeaturesReply) GetNextAfter() string {
	if x != nil && x.NextAfter != nil {
		return *x.NextAfter
	}
	return ""
}

type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Dataset       string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	FeatureId     string                 `protobuf:"bytes,3,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Base          *Feature               `protobuf:"bytes,4,opt,name=base,proto3" json:"base,omitempty"`
	Draft         *Feature               `protobuf:"bytes,5,opt,name=draft,proto3" json:"draft,omitempty"`
	Before        *Feature               `protobuf:"bytes,6,opt,name=before,proto3" json:"before,omitempty"`
	After         *Feature               `protobuf:"bytes,7,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{30}
}

func (x *Change) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Change) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Change) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *Change) GetBase() *Feature {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Change) GetDraft() *Feature {
	if x != nil {
		return x.Draft
	}
	return nil
}

func (x *Change) GetBefore() *Feature {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Change) GetAfter() *Feature {
	if x != nil {
		return x.After
	}
	return nil
}

type DiffReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRevision  int64                  `protobuf:"varint,1,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Changes       []*Change              `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffReply) Reset() {
	*x = DiffReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffReply) ProtoMessage() {}

func (x *DiffReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffReply.ProtoReflect.Descriptor instead.
func (*DiffReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{31}
}

func (x *DiffReply) GetBaseRevision() int64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

func (x *DiffReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DiffReply) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Conflict struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Cursor                  string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Dataset                 string                 `protobuf:"bytes,2,opt,name=dataset,proto3" json:"dataset,omitempty"`
	FeatureId               string                 `protobuf:"bytes,3,opt,name=feature_id,json=featureId,proto3" json:"feature_id,omitempty"`
	Fields                  []string               `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Base                    *Feature               `protobuf:"bytes,5,opt,name=base,proto3" json:"base,omitempty"`
	Current                 *Feature               `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	Draft                   *Feature               `protobuf:"bytes,7,opt,name=draft,proto3" json:"draft,omitempty"`
	Reason                  string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ResolvedAgainstRevision *int64                 `protobuf:"varint,9,opt,name=resolved_against_revision,json=resolvedAgainstRevision,proto3,oneof" json:"resolved_against_revision,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{32}
}

func (x *Conflict) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Conflict) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Conflict) GetFeatureId() string {
	if x != nil {
		return x.FeatureId
	}
	return ""
}

func (x *Conflict) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Conflict) GetBase() *Feature {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Conflict) GetCurrent() *Feature {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *Conflict) GetDraft() *Feature {
	if x != nil {
		return x.Draft
	}
	return nil
}

func (x *Conflict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Conflict) GetResolvedAgainstRevision() int64 {
	if x != nil && x.ResolvedAgainstRevision != nil {
		return *x.ResolvedAgainstRevision
	}
	return 0
}

type ConflictsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          int64                  `protobuf:"varint,1,opt,name=head,proto3" json:"head,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	NextAfter     *string                `protobuf:"bytes,4,opt,name=next_after,json=nextAfter,proto3,oneof" json:"next_after,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,6,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictsReply) Reset() {
	*x = ConflictsReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsReply) ProtoMessage() {}

func (x *ConflictsReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsReply.ProtoReflect.Descriptor instead.
func (*ConflictsReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{33}
}

func (x *ConflictsReply) GetHead() int64 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *ConflictsReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConflictsReply) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConflictsReply) GetNextAfter() string {
	if x != nil && x.NextAfter != nil {
		return *x.NextAfter
	}
	return ""
}

func (x *ConflictsReply) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ConflictsReply) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type CommitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInfo) Reset() {
	*x = CommitInfo{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfo) ProtoMessage() {}

func (x *CommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfo.ProtoReflect.Descriptor instead.
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{34}
}

func (x *CommitInfo) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CommitInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CommitInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type HistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitInfo          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryReply) Reset() {
	*x = HistoryReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReply) ProtoMessage() {}

func (x *HistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReply.ProtoReflect.Descriptor instead.
func (*HistoryReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{35}
}

func (x *HistoryReply) GetCommits() []*CommitInfo {
	if x != nil {
		return x.Commits
	}
	return nil
}

type CommitReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Changes       []*Change              `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReply) Reset() {
	*x = CommitReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReply) ProtoMessage() {}

func (x *CommitReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReply.ProtoReflect.Descriptor instead.
func (*CommitReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{36}
}

func (x *CommitReply) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CommitReply) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	DetailJson    string                 `protobuf:"bytes,4,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{37}
}

func (x *AuditEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *AuditEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AuditReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextAfter     *int64                 `protobuf:"varint,2,opt,name=next_after,json=nextAfter,proto3,oneof" json:"next_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReply) Reset() {
	*x = AuditReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReply) ProtoMessage() {}

func (x *AuditReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReply.ProtoReflect.Descriptor instead.
func (*AuditReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{38}
}

func (x *AuditReply) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AuditReply) GetNextAfter() int64 {
	if x != nil && x.NextAfter != nil {
		return *x.NextAfter
	}
	return 0
}

type PublishReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Changes       uint64                 `protobuf:"varint,5,opt,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{39}
}

func (x *PublishReply) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PublishReply) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *PublishReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PublishReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublishReply) GetChanges() uint64 {
	if x != nil {
		return x.Changes
	}
	return 0
}

type ResolveReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Head               int64                  `protobuf:"varint,1,opt,name=head,proto3" json:"head,omitempty"`
	Version            int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	RemainingConflicts uint64                 `protobuf:"varint,3,opt,name=remaining_conflicts,json=remainingConflicts,proto3" json:"remaining_conflicts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResolveReply) Reset() {
	*x = ResolveReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveReply) ProtoMessage() {}

func (x *ResolveReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveReply.ProtoReflect.Descriptor instead.
func (*ResolveReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{40}
}

func (x *ResolveReply) GetHead() int64 {
	if x != nil {
		return x.Head
	}
	return 0
}

func (x *ResolveReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResolveReply) GetRemainingConflicts() uint64 {
	if x != nil {
		return x.RemainingConflicts
	}
	return 0
}

type RebaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseRevision  int64                  `protobuf:"varint,1,opt,name=base_revision,json=baseRevision,proto3" json:"base_revision,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Changes       uint64                 `protobuf:"varint,3,opt,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseReply) Reset() {
	*x = RebaseReply{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseReply) ProtoMessage() {}

func (x *RebaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseReply.ProtoReflect.Descriptor instead.
func (*RebaseReply) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{41}
}

func (x *RebaseReply) GetBaseRevision() int64 {
	if x != nil {
		return x.BaseRevision
	}
	return 0
}

func (x *RebaseReply) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RebaseReply) GetChanges() uint64 {
	if x != nil {
		return x.Changes
	}
	return 0
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Conflicts     *ConflictsReply        `protobuf:"bytes,4,opt,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{42}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ErrorDetail) GetConflicts() *ConflictsReply {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

// Wire-compatible google.rpc.Status / google.protobuf.Any envelopes. These avoid
// a runtime dependency on Google common-proto packages in generated clients.
// grpc-status-details-bin always contains this envelope, never a bare ErrorDetail.
type RpcStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*ErrorAny            `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcStatus) Reset() {
	*x = RpcStatus{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcStatus) ProtoMessage() {}

func (x *RpcStatus) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcStatus.ProtoReflect.Descriptor instead.
func (*RpcStatus) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{43}
}

func (x *RpcStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RpcStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcStatus) GetDetails() []*ErrorAny {
	if x != nil {
		return x.Details
	}
	return nil
}

type ErrorAny struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeUrl       string                 `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorAny) Reset() {
	*x = ErrorAny{}
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorAny) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorAny) ProtoMessage() {}

func (x *ErrorAny) ProtoReflect() protoreflect.Message {
	mi := &file_geoledger_v1_geoledger_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorAny.ProtoReflect.Descriptor instead.
func (*ErrorAny) Descriptor() ([]byte, []int) {
	return file_geoledger_v1_geoledger_proto_rawDescGZIP(), []int{44}
}

func (x *ErrorAny) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *ErrorAny) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_geoledger_v1_geoledger_proto protoreflect.FileDescriptor

const file_geoledger_v1_geoledger_proto_rawDesc = "" +
	"\n" +
	"\x1cgeoledger/v1/geoledger.proto\x12\fgeoledger.v1\"!\n" +
	"\vNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x0eProjectRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"H\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\tR\x05after\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x03H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"i\n" +
	"\x12ProjectPageRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x14\n" +
	"\x05after\x18\x02 \x01(\tR\x05after\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"W\n" +
	"\rMemberRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\">\n" +
	"\x0eDatasetRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"J\n" +
	"\x10WorkspaceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"\x86\x01\n" +
	"\x0eVersionRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12<\n" +
	"\x1aexpected_workspace_version\x18\x03 \x01(\x03R\x18expectedWorkspaceVersion\"#\n" +
	"\aFeature\x12\x18\n" +
	"\ageojson\x18\x01 \x01(\tR\ageojson\"p\n" +
	"\x04Edit\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x02 \x01(\tR\tfeatureId\x12/\n" +
	"\afeature\x18\x03 \x01(\v2\x15.geoledger.v1.FeatureR\afeature\"\xad\x01\n" +
	"\vSaveRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12<\n" +
	"\x1aexpected_workspace_version\x18\x03 \x01(\x03R\x18expectedWorkspaceVersion\x12(\n" +
	"\x05edits\x18\x04 \x03(\v2\x12.geoledger.v1.EditR\x05edits\"\xa6\x02\n" +
	"\x0fFeaturesRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12!\n" +
	"\tworkspace\x18\x03 \x01(\tH\x00R\tworkspace\x88\x01\x01\x12\x1f\n" +
	"\brevision\x18\x04 \x01(\x03H\x01R\brevision\x88\x01\x01\x12\"\n" +
	"\n" +
	"feature_id\x18\x05 \x01(\tH\x02R\tfeatureId\x88\x01\x01\x12\x12\n" +
	"\x04bbox\x18\x06 \x03(\x01R\x04bbox\x12\x14\n" +
	"\x05after\x18\a \x01(\tR\x05after\x12\x19\n" +
	"\x05limit\x18\b \x01(\x03H\x03R\x05limit\x88\x01\x01B\f\n" +
	"\n" +
	"_workspaceB\v\n" +
	"\t_revisionB\r\n" +
	"\v_feature_idB\b\n" +
	"\x06_limit\"\x80\x01\n" +
	"\vDiffRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x03H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"e\n" +
	"\x0eHistoryRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x03R\x05after\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x03H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\x80\x01\n" +
	"\rCommitRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x03H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\xbf\x01\n" +
	"\x0ePublishRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12<\n" +
	"\x1aexpected_workspace_version\x18\x03 \x01(\x03R\x18expectedWorkspaceVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x0eResolveRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12<\n" +
	"\x1aexpected_workspace_version\x18\x03 \x01(\x03R\x18expectedWorkspaceVersion\x12#\n" +
	"\rexpected_head\x18\x04 \x01(\x03R\fexpectedHead\x124\n" +
	"\vresolutions\x18\x05 \x03(\v2\x12.geoledger.v1.EditR\vresolutions\"F\n" +
	"\x0eRestoreRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\"\a\n" +
	"\x05Empty\"\xbe\x01\n" +
	"\tInfoReply\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12%\n" +
	"\x0eformat_version\x18\x03 \x01(\rR\rformatVersion\x12*\n" +
	"\x11max_request_bytes\x18\x04 \x01(\rR\x0fmaxRequestBytes\x12*\n" +
	"\x11max_feature_bytes\x18\x05 \x01(\rR\x0fmaxFeatureBytes\"d\n" +
	"\fProjectReply\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04head\x18\x03 \x01(\x03R\x04head\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"G\n" +
	"\rProjectsReply\x126\n" +
	"\bprojects\x18\x01 \x03(\v2\x1a.geoledger.v1.ProjectReplyR\bprojects\"\x19\n" +
	"\aOkReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"<\n" +
	"\fDatasetReply\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\rDatasetsReply\x126\n" +
	"\bdatasets\x18\x01 \x03(\v2\x1a.geoledger.v1.DatasetReplyR\bdatasets\"\x85\x01\n" +
	"\x0eWorkspaceReply\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12#\n" +
	"\rbase_revision\x18\x02 \x01(\x03R\fbaseRevision\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"O\n" +
	"\x0fWorkspacesReply\x12<\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1c.geoledger.v1.WorkspaceReplyR\n" +
	"workspaces\"?\n" +
	"\tSaveReply\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x18\n" +
	"\achanges\x18\x02 \x01(\x03R\achanges\"@\n" +
	"\fDiscardReply\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xd9\x01\n" +
	"\rFeaturesReply\x121\n" +
	"\bfeatures\x18\x01 \x03(\v2\x15.geoledger.v1.FeatureR\bfeatures\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x120\n" +
	"\x11workspace_version\x18\x03 \x01(\x03H\x00R\x10workspaceVersion\x88\x01\x01\x12\"\n" +
	"\n" +
	"next_after\x18\x04 \x01(\tH\x01R\tnextAfter\x88\x01\x01B\x14\n" +
	"\x12_workspace_versionB\r\n" +
	"\v_next_after\"\x8d\x02\n" +
	"\x06Change\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x03 \x01(\tR\tfeatureId\x12)\n" +
	"\x04base\x18\x04 \x01(\v2\x15.geoledger.v1.FeatureR\x04base\x12+\n" +
	"\x05draft\x18\x05 \x01(\v2\x15.geoledger.v1.FeatureR\x05draft\x12-\n" +
	"\x06before\x18\x06 \x01(\v2\x15.geoledger.v1.FeatureR\x06before\x12+\n" +
	"\x05after\x18\a \x01(\v2\x15.geoledger.v1.FeatureR\x05after\"z\n" +
	"\tDiffReply\x12#\n" +
	"\rbase_revision\x18\x01 \x01(\x03R\fbaseRevision\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12.\n" +
	"\achanges\x18\x03 \x03(\v2\x14.geoledger.v1.ChangeR\achanges\"\xf3\x02\n" +
	"\bConflict\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x18\n" +
	"\adataset\x18\x02 \x01(\tR\adataset\x12\x1d\n" +
	"\n" +
	"feature_id\x18\x03 \x01(\tR\tfeatureId\x12\x16\n" +
	"\x06fields\x18\x04 \x03(\tR\x06fields\x12)\n" +
	"\x04base\x18\x05 \x01(\v2\x15.geoledger.v1.FeatureR\x04base\x12/\n" +
	"\acurrent\x18\x06 \x01(\v2\x15.geoledger.v1.FeatureR\acurrent\x12+\n" +
	"\x05draft\x18\a \x01(\v2\x15.geoledger.v1.FeatureR\x05draft\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12?\n" +
	"\x19resolved_against_revision\x18\t \x01(\x03H\x00R\x17resolvedAgainstRevision\x88\x01\x01B\x1c\n" +
	"\x1a_resolved_against_revision\"\xdb\x01\n" +
	"\x0eConflictsReply\x12\x12\n" +
	"\x04head\x18\x01 \x01(\x03R\x04head\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\"\n" +
	"\n" +
	"next_after\x18\x04 \x01(\tH\x00R\tnextAfter\x88\x01\x01\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x124\n" +
	"\tconflicts\x18\x06 \x03(\v2\x16.geoledger.v1.ConflictR\tconflictsB\r\n" +
	"\v_next_after\"{\n" +
	"\n" +
	"CommitInfo\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"B\n" +
	"\fHistoryReply\x122\n" +
	"\acommits\x18\x01 \x03(\v2\x18.geoledger.v1.CommitInfoR\acommits\"Y\n" +
	"\vCommitReply\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12.\n" +
	"\achanges\x18\x02 \x03(\v2\x14.geoledger.v1.ChangeR\achanges\"\x8e\x01\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vdetail_json\x18\x04 \x01(\tR\n" +
	"detailJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"q\n" +
	"\n" +
	"AuditReply\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.geoledger.v1.AuditEventR\x06events\x12\"\n" +
	"\n" +
	"next_after\x18\x02 \x01(\x03H\x00R\tnextAfter\x88\x01\x01B\r\n" +
	"\v_next_after\"\x94\x01\n" +
	"\fPublishReply\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\achanges\x18\x05 \x01(\x04R\achanges\"m\n" +
	"\fResolveReply\x12\x12\n" +
	"\x04head\x18\x01 \x01(\x03R\x04head\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12/\n" +
	"\x13remaining_conflicts\x18\x03 \x01(\x04R\x12remainingConflicts\"f\n" +
	"\vRebaseReply\x12#\n" +
	"\rbase_revision\x18\x01 \x01(\x03R\fbaseRevision\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x18\n" +
	"\achanges\x18\x03 \x01(\x04R\achanges\"\x96\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12:\n" +
	"\tconflicts\x18\x04 \x01(\v2\x1c.geoledger.v1.ConflictsReplyR\tconflicts\"k\n" +
	"\tRpcStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\adetails\x18\x03 \x03(\v2\x16.geoledger.v1.ErrorAnyR\adetails\";\n" +
	"\bErrorAny\x12\x19\n" +
	"\btype_url\x18\x01 \x01(\tR\atypeUrl\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value2\x8b\f\n" +
	"\tGeoLedger\x124\n" +
	"\x04Info\x12\x13.geoledger.v1.Empty\x1a\x17.geoledger.v1.InfoReply\x12F\n" +
	"\rCreateProject\x12\x19.geoledger.v1.NameRequest\x1a\x1a.geoledger.v1.ProjectReply\x12F\n" +
	"\fListProjects\x12\x19.geoledger.v1.PageRequest\x1a\x1b.geoledger.v1.ProjectsReply\x12F\n" +
	"\n" +
	"GetProject\x12\x1c.geoledger.v1.ProjectRequest\x1a\x1a.geoledger.v1.ProjectReply\x12?\n" +
	"\tSetMember\x12\x1b.geoledger.v1.MemberRequest\x1a\x15.geoledger.v1.OkReply\x12I\n" +
	"\rCreateDataset\x12\x1c.geoledger.v1.DatasetRequest\x1a\x1a.geoledger.v1.DatasetReply\x12M\n" +
	"\fListDatasets\x12 .geoledger.v1.ProjectPageRequest\x1a\x1b.geoledger.v1.DatasetsReply\x12M\n" +
	"\x0fCreateWorkspace\x12\x1c.geoledger.v1.ProjectRequest\x1a\x1c.geoledger.v1.WorkspaceReply\x12Q\n" +
	"\x0eListWorkspaces\x12 .geoledger.v1.ProjectPageRequest\x1a\x1d.geoledger.v1.WorkspacesReply\x12L\n" +
	"\fGetWorkspace\x12\x1e.geoledger.v1.WorkspaceRequest\x1a\x1c.geoledger.v1.WorkspaceReply\x12:\n" +
	"\x04Save\x12\x19.geoledger.v1.SaveRequest\x1a\x17.geoledger.v1.SaveReply\x12C\n" +
	"\aDiscard\x12\x1c.geoledger.v1.VersionRequest\x1a\x1a.geoledger.v1.DiscardReply\x12F\n" +
	"\bFeatures\x12\x1d.geoledger.v1.FeaturesRequest\x1a\x1b.geoledger.v1.FeaturesReply\x12:\n" +
	"\x04Diff\x12\x19.geoledger.v1.DiffRequest\x1a\x17.geoledger.v1.DiffReply\x12D\n" +
	"\tConflicts\x12\x19.geoledger.v1.DiffRequest\x1a\x1c.geoledger.v1.ConflictsReply\x12C\n" +
	"\aHistory\x12\x1c.geoledger.v1.HistoryRequest\x1a\x1a.geoledger.v1.HistoryReply\x12@\n" +
	"\x06Commit\x12\x1b.geoledger.v1.CommitRequest\x1a\x19.geoledger.v1.CommitReply\x12?\n" +
	"\x05Audit\x12\x1c.geoledger.v1.HistoryRequest\x1a\x18.geoledger.v1.AuditReply\x12C\n" +
	"\aPublish\x12\x1c.geoledger.v1.PublishRequest\x1a\x1a.geoledger.v1.PublishReply\x12C\n" +
	"\aResolve\x12\x1c.geoledger.v1.ResolveRequest\x1a\x1a.geoledger.v1.ResolveReply\x12A\n" +
	"\x06Rebase\x12\x1c.geoledger.v1.ResolveRequest\x1a\x19.geoledger.v1.RebaseReply\x12E\n" +
	"\aRestore\x12\x1c.geoledger.v1.RestoreRequest\x1a\x1c.geoledger.v1.WorkspaceReplyB<Z:github.com/mapseekai/geoledger/sdk/go/internal/geoledgerv1b\x06proto3"

var (
	file_geoledger_v1_geoledger_proto_rawDescOnce sync.Once
	file_geoledger_v1_geoledger_proto_rawDescData []byte
)

func file_geoledger_v1_geoledger_proto_rawDescGZIP() []byte {
	file_geoledger_v1_geoledger_proto_rawDescOnce.Do(func() {
		file_geoledger_v1_geoledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoledger_v1_geoledger_proto_rawDesc), len(file_geoledger_v1_geoledger_proto_rawDesc)))
	})
	return file_geoledger_v1_geoledger_proto_rawDescData
}

var file_geoledger_v1_geoledger_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_geoledger_v1_geoledger_proto_goTypes = []any{
	(*NameRequest)(nil),        // 0: geoledger.v1.NameRequest
	(*ProjectRequest)(nil),     // 1: geoledger.v1.ProjectRequest
	(*PageRequest)(nil),        // 2: geoledger.v1.PageRequest
	(*ProjectPageRequest)(nil), // 3: geoledger.v1.ProjectPageRequest
	(*MemberRequest)(nil),      // 4: geoledger.v1.MemberRequest
	(*DatasetRequest)(nil),     // 5: geoledger.v1.DatasetRequest
	(*WorkspaceRequest)(nil),   // 6: geoledger.v1.WorkspaceRequest
	(*VersionRequest)(nil),     // 7: geoledger.v1.VersionRequest
	(*Feature)(nil),            // 8: geoledger.v1.Feature
	(*Edit)(nil),               // 9: geoledger.v1.Edit
	(*SaveRequest)(nil),        // 10: geoledger.v1.SaveRequest
	(*FeaturesRequest)(nil),    // 11: geoledger.v1.FeaturesRequest
	(*DiffRequest)(nil),        // 12: geoledger.v1.DiffRequest
	(*HistoryRequest)(nil),     // 13: geoledger.v1.HistoryRequest
	(*CommitRequest)(nil),      // 14: geoledger.v1.CommitRequest
	(*PublishRequest)(nil),     // 15: geoledger.v1.PublishRequest
	(*ResolveRequest)(nil),     // 16: geoledger.v1.ResolveRequest
	(*RestoreRequest)(nil),     // 17: geoledger.v1.RestoreRequest
	(*Empty)(nil),              // 18: geoledger.v1.Empty
	(*InfoReply)(nil),          // 19: geoledger.v1.InfoReply
	(*ProjectReply)(nil),       // 20: geoledger.v1.ProjectReply
	(*ProjectsReply)(nil),      // 21: geoledger.v1.ProjectsReply
	(*OkReply)(nil),            // 22: geoledger.v1.OkReply
	(*DatasetReply)(nil),       // 23: geoledger.v1.DatasetReply
	(*DatasetsReply)(nil),      // 24: geoledger.v1.DatasetsReply
	(*WorkspaceReply)(nil),     // 25: geoledger.v1.WorkspaceReply
	(*WorkspacesReply)(nil),    // 26: geoledger.v1.WorkspacesReply
	(*SaveReply)(nil),          // 27: geoledger.v1.SaveReply
	(*DiscardReply)(nil),       // 28: geoledger.v1.DiscardReply
	(*FeaturesReply)(nil),      // 29: geoledger.v1.FeaturesReply
	(*Change)(nil),             // 30: geoledger.v1.Change
	(*DiffReply)(nil),          // 31: geoledger.v1.DiffReply
	(*Conflict)(nil),           // 32: geoledger.v1.Conflict
	(*ConflictsReply)(nil),     // 33: geoledger.v1.ConflictsReply
	(*CommitInfo)(nil),         // 34: geoledger.v1.CommitInfo
	(*HistoryReply)(nil),       // 35: geoledger.v1.HistoryReply
	(*CommitReply)(nil),        // 36: geoledger.v1.CommitReply
	(*AuditEvent)(nil),         // 37: geoledger.v1.AuditEvent
	(*AuditReply)(nil),         // 38: geoledger.v1.AuditReply
	(*PublishReply)(nil),       // 39: geoledger.v1.PublishReply
	(*ResolveReply)(nil),       // 40: geoledger.v1.ResolveReply
	(*RebaseReply)(nil),        // 41: geoledger.v1.RebaseReply
	(*ErrorDetail)(nil),        // 42: geoledger.v1.ErrorDetail
	(*RpcStatus)(nil),          // 43: geoledger.v1.RpcStatus
	(*ErrorAny)(nil),           // 44: geoledger.v1.ErrorAny
}
var file_geoledger_v1_geoledger_proto_depIdxs = []int32{
	8,  // 0: geoledger.v1.Edit.feature:type_name -> geoledger.v1.Feature
	9,  // 1: geoledger.v1.SaveRequest.edits:type_name -> geoledger.v1.Edit
	9,  // 2: geoledger.v1.ResolveRequest.resolutions:type_name -> geoledger.v1.Edit
	20, // 3: geoledger.v1.ProjectsReply.projects:type_name -> geoledger.v1.ProjectReply
	23, // 4: geoledger.v1.DatasetsReply.datasets:type_name -> geoledger.v1.DatasetReply
	25, // 5: geoledger.v1.WorkspacesReply.workspaces:type_name -> geoledger.v1.WorkspaceReply
	8,  // 6: geoledger.v1.FeaturesReply.features:type_name -> geoledger.v1.Feature
	8,  // 7: geoledger.v1.Change.base:type_name -> geoledger.v1.Feature
	8,  // 8: geoledger.v1.Change.draft:type_name -> geoledger.v1.Feature
	8,  // 9: geoledger.v1.Change.before:type_name -> geoledger.v1.Feature
	8,  // 10: geoledger.v1.Change.after:type_name -> geoledger.v1.Feature
	30, // 11: geoledger.v1.DiffReply.changes:type_name -> geoledger.v1.Change
	8,  // 12: geoledger.v1.Conflict.base:type_name -> geoledger.v1.Feature
	8,  // 13: geoledger.v1.Conflict.current:type_name -> geoledger.v1.Feature
	8,  // 14: geoledger.v1.Conflict.draft:type_name -> geoledger.v1.Feature
	32, // 15: geoledger.v1.ConflictsReply.conflicts:type_name -> geoledger.v1.Conflict
	34, // 16: geoledger.v1.HistoryReply.commits:type_name -> geoledger.v1.CommitInfo
	30, // 17: geoledger.v1.CommitReply.changes:type_name -> geoledger.v1.Change
	37, // 18: geoledger.v1.AuditReply.events:type_name -> geoledger.v1.AuditEvent
	33, // 19: geoledger.v1.ErrorDetail.conflicts:type_name -> geoledger.v1.ConflictsReply
	44, // 20: geoledger.v1.RpcStatus.details:type_name -> geoledger.v1.ErrorAny
	18, // 21: geoledger.v1.GeoLedger.Info:input_type -> geoledger.v1.Empty
	0,  // 22: geoledger.v1.GeoLedger.CreateProject:input_type -> geoledger.v1.NameRequest
	2,  // 23: geoledger.v1.GeoLedger.ListProjects:input_type -> geoledger.v1.PageRequest
	1,  // 24: geoledger.v1.GeoLedger.GetProject:input_type -> geoledger.v1.ProjectRequest
	4,  // 25: geoledger.v1.GeoLedger.SetMember:input_type -> geoledger.v1.MemberRequest
	5,  // 26: geoledger.v1.GeoLedger.CreateDataset:input_type -> geoledger.v1.DatasetRequest
	3,  // 27: geoledger.v1.GeoLedger.ListDatasets:input_type -> geoledger.v1.ProjectPageRequest
	1,  // 28: geoledger.v1.GeoLedger.CreateWorkspace:input_type -> geoledger.v1.ProjectRequest
	3,  // 29: geoledger.v1.GeoLedger.ListWorkspaces:input_type -> geoledger.v1.ProjectPageRequest
	6,  // 30: geoledger.v1.GeoLedger.GetWorkspace:input_type -> geoledger.v1.WorkspaceRequest
	10, // 31: geoledger.v1.GeoLedger.Save:input_type -> geoledger.v1.SaveRequest
	7,  // 32: geoledger.v1.GeoLedger.Discard:input_type -> geoledger.v1.VersionRequest
	11, // 33: geoledger.v1.GeoLedger.Features:input_type -> geoledger.v1.FeaturesRequest
	12, // 34: geoledger.v1.GeoLedger.Diff:input_type -> geoledger.v1.DiffRequest
	12, // 35: geoledger.v1.GeoLedger.Conflicts:input_type -> geoledger.v1.DiffRequest
	13, // 36: geoledger.v1.GeoLedger.History:input_type -> geoledger.v1.HistoryRequest
	14, // 37: geoledger.v1.GeoLedger.Commit:input_type -> geoledger.v1.CommitRequest
	13, // 38: geoledger.v1.GeoLedger.Audit:input_type -> geoledger.v1.HistoryRequest
	15, // 39: geoledger.v1.GeoLedger.Publish:input_type -> geoledger.v1.PublishRequest
	16, // 40: geoledger.v1.GeoLedger.Resolve:input_type -> geoledger.v1.ResolveRequest
	16, // 41: geoledger.v1.GeoLedger.Rebase:input_type -> geoledger.v1.ResolveRequest
	17, // 42: geoledger.v1.GeoLedger.Restore:input_type -> geoledger.v1.RestoreRequest
	19, // 43: geoledger.v1.GeoLedger.Info:output_type -> geoledger.v1.InfoReply
	20, // 44: geoledger.v1.GeoLedger.CreateProject:output_type -> geoledger.v1.ProjectReply
	21, // 45: geoledger.v1.GeoLedger.ListProjects:output_type -> geoledger.v1.ProjectsReply
	20, // 46: geoledger.v1.GeoLedger.GetProject:output_type -> geoledger.v1.ProjectReply
	22, // 47: geoledger.v1.GeoLedger.SetMember:output_type -> geoledger.v1.OkReply
	23, // 48: geoledger.v1.GeoLedger.CreateDataset:output_type -> geoledger.v1.DatasetReply
	24, // 49: geoledger.v1.GeoLedger.ListDatasets:output_type -> geoledger.v1.DatasetsReply
	25, // 50: geoledger.v1.GeoLedger.CreateWorkspace:output_type -> geoledger.v1.WorkspaceReply
	26, // 51: geoledger.v1.GeoLedger.ListWorkspaces:output_type -> geoledger.v1.WorkspacesReply
	25, // 52: geoledger.v1.GeoLedger.GetWorkspace:output_type -> geoledger.v1.WorkspaceReply
	27, // 53: geoledger.v1.GeoLedger.Save:output_type -> geoledger.v1.SaveReply
	28, // 54: geoledger.v1.GeoLedger.Discard:output_type -> geoledger.v1.DiscardReply
	29, // 55: geoledger.v1.GeoLedger.Features:output_type -> geoledger.v1.FeaturesReply
	31, // 56: geoledger.v1.GeoLedger.Diff:output_type -> geoledger.v1.DiffReply
	33, // 57: geoledger.v1.GeoLedger.Conflicts:output_type -> geoledger.v1.ConflictsReply
	35, // 58: geoledger.v1.GeoLedger.History:output_type -> geoledger.v1.HistoryReply
	36, // 59: geoledger.v1.GeoLedger.Commit:output_type -> geoledger.v1.CommitReply
	38, // 60: geoledger.v1.GeoLedger.Audit:output_type -> geoledger.v1.AuditReply
	39, // 61: geoledger.v1.GeoLedger.Publish:output_type -> geoledger.v1.PublishReply
	40, // 62: geoledger.v1.GeoLedger.Resolve:output_type -> geoledger.v1.ResolveReply
	41, // 63: geoledger.v1.GeoLedger.Rebase:output_type -> geoledger.v1.RebaseReply
	25, // 64: geoledger.v1.GeoLedger.Restore:output_type -> geoledger.v1.WorkspaceReply
	43, // [43:65] is the sub-list for method output_type
	21, // [21:43] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_geoledger_v1_geoledger_proto_init() }
func file_geoledger_v1_geoledger_proto_init() {
	if File_geoledger_v1_geoledger_proto != nil {
		return
	}
	file_geoledger_v1_geoledger_proto_msgTypes[2].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[3].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[11].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[12].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[13].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[14].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[29].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[32].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[33].OneofWrappers = []any{}
	file_geoledger_v1_geoledger_proto_msgTypes[38].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoledger_v1_geoledger_proto_rawDesc), len(file_geoledger_v1_geoledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geoledger_v1_geoledger_proto_goTypes,
		DependencyIndexes: file_geoledger_v1_geoledger_proto_depIdxs,
		MessageInfos:      file_geoledger_v1_geoledger_proto_msgTypes,
	}.Build()
	File_geoledger_v1_geoledger_proto = out.File
	file_geoledger_v1_geoledger_proto_goTypes = nil
	file_geoledger_v1_geoledger_proto_depIdxs = nil
}
